BBS/urls.py
from django.contrib import admin
from django.urls import path,re_path,include
from blog import views
from blog import urls as blog_urls
from django.views.static import serve
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('upload/', views.upload),
    path('login/', views.login),
    path('logout/', views.logout),
    path('index/', views.index),
    path('blog/', include("blog.urls")),
    path('register/', views.register),
    path('blog-reg/', views.blog_reg),
    re_path(r'^media/(?P<path>.*)$', serve, {"document_root": settings.MEDIA_ROOT}),
    path('check_username_exist/', views.check_username_exist),
    re_path('^pc-geetest/register', views.get_geetest),
]

blog/urls.py
from django.contrib import admin
from django.urls import path,re_path
from blog import views


urlpatterns = [
    # url和下方重复，放在上面比较好
    path("create/", views.create),

    path("up_down/", views.up_down),
    path("comment/", views.comment),
    path('<str:site>/', views.home),
    path('<str:site>/tag/<str:tag>/', views.tag),
    path('<str:site>/category/<str:category>/', views.category),

    path('<str:site>/articles/<int:article_id>/', views.article),
    ]

blog/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class UserInfo(AbstractUser):
    """用户信息表"""
    nid = models.AutoField(primary_key=True)
    phone = models.CharField(max_length=11,null=True,blank=True,unique=True)
    avatar = models.FileField(upload_to="media/avatars/",default="static/avatars/default.png", verbose_name="头像")
    create_time = models.DateTimeField(auto_now_add=True)

    blog = models.OneToOneField(to="Blog",to_field='nid',null=True,blank=True,on_delete=models.CASCADE)

    def __str__(self):
        return self.username

    class Meta:
        verbose_name = "用户"
        verbose_name_plural = verbose_name


class Blog(models.Model):
    """博客信息"""
    nid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=64)
    site = models.CharField(max_length=32,unique=True)  #个人博客域名
    theme = models.CharField(max_length=32)  #博客主题

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "blog站点"
        verbose_name_plural = verbose_name


class Article(models.Model):
    """文章信息"""
    nid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=50,verbose_name="文章标题")
    user = models.ForeignKey(to='UserInfo',to_field='nid',verbose_name="作者",on_delete=models.CASCADE)
    desc = models.CharField(max_length=255,verbose_name="文章描述")
    create_time = models.DateTimeField(auto_now_add=True,verbose_name="创建时间")

    comment_count = models.IntegerField(default=0,verbose_name="评论数")
    up_count = models.IntegerField(default=0,verbose_name="点赞数")
    down_count = models.IntegerField(default=0,verbose_name="踩数")

    category = models.ForeignKey(to="Category", to_field="nid", null=True,on_delete=models.CASCADE)
    tag = models.ManyToManyField(
        to="Tag",
        through="Article2Tag",
        through_fields=("article", "tag"),
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "文章"
        verbose_name_plural = verbose_name


class Category(models.Model):
    """分类"""
    nid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=32)
    blog = models.ForeignKey(to="Blog", to_field="nid",on_delete=models.CASCADE)  # 外键关联博客，一个博客站点可以有多个分类

    def __str__(self):
        return "%s-%s"%(self.blog,self.title)
    class Meta:
        unique_together=(("title","blog"),)
        verbose_name = "文章分类"
        verbose_name_plural = verbose_name


class Tag(models.Model):
    """标签"""
    nid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=32,verbose_name="标签名")
    blog = models.ForeignKey(to="Blog", to_field="nid",on_delete=models.CASCADE)  # 所属博客

    def __str__(self):
        return "%s-%s"%(self.blog,self.title)

    class Meta:
        verbose_name = "标签"
        verbose_name_plural = verbose_name


class Article2Tag(models.Model):
    """"文章和标签的多对多关系表"""
    nid = models.AutoField(primary_key=True)
    article = models.ForeignKey(to="Article", to_field="nid",verbose_name="文章名",on_delete=models.CASCADE)
    tag = models.ForeignKey(to="Tag", to_field="nid",verbose_name="标签名",on_delete=models.CASCADE)

    def __str__(self):
        return "{}-{}".format(self.article.title, self.tag.title)

    class Meta:
        unique_together = (("article", "tag"),)
        verbose_name = "文章-标签"
        verbose_name_plural = verbose_name


class ArticleDetail(models.Model):
    """文章详情表"""
    nid = models.AutoField(primary_key=True)
    content = models.TextField()
    article = models.OneToOneField(to="Article", to_field="nid",on_delete=models.CASCADE)

    def __str__(self):
        return self.article.title
    class Meta:
        verbose_name = "文章详情"
        verbose_name_plural = verbose_name


class ArticleUpDown(models.Model):
    """点赞表"""
    nid = models.AutoField(primary_key=True)
    user = models.ForeignKey(to="UserInfo", null=True,on_delete=models.CASCADE)
    article = models.ForeignKey(to="Article", null=True,on_delete=models.CASCADE)
    is_up = models.BooleanField(default=True)

    def __str__(self):
        return self.article.title
    class Meta:
        unique_together = (("article", "user"),)
        verbose_name = "文章点赞"
        verbose_name_plural = verbose_name


class Comment(models.Model):
    """评论表"""
    nid = models.AutoField(primary_key=True)
    article = models.ForeignKey(to="Article", to_field="nid",on_delete=models.CASCADE)
    user = models.ForeignKey(to="UserInfo", to_field="nid",on_delete=models.CASCADE)
    content = models.CharField(max_length=255)  # 评论内容
    create_time = models.DateTimeField(auto_now_add=True)
    parent_comment = models.ForeignKey("self", null=True, blank=True,on_delete=models.CASCADE)

    def __str__(self):
        return self.content

    class Meta:
        verbose_name = "评论"
        verbose_name_plural = verbose_name

blog/forms.py
from django import forms
from django.core.exceptions import ValidationError
from blog import models


# 定义一个注册的form类
class RegForm(forms.Form):
    username = forms.CharField(
        max_length=16,
        label="用户名",
        error_messages={
            "max_length": "用户名最长16位",
            "required": "用户名不能为空",
        },

        widget=forms.widgets.TextInput(
            attrs={"class": "form-control"},
        )
    )

    password = forms.CharField(
        min_length=6,
        label="密码",
        widget=forms.widgets.PasswordInput(
            attrs={"class": "form-control"},
            render_value=True,
        ),
        error_messages={
            "min_length": "密码至少要6位！",
            "required": "密码不能为空",
        }
    )

    re_password = forms.CharField(
        min_length=6,
        label="确认密码",
        widget=forms.widgets.PasswordInput(
            attrs={"class": "form-control"},
            render_value=True,
        ),
        error_messages={
            "min_length": "确认密码至少要6位！",
            "required": "确认密码不能为空",
        }
    )

    email = forms.EmailField(
        label="邮箱",
        widget=forms.widgets.EmailInput(
            attrs={"class": "form-control"},

        ),
        error_messages={
            "invalid": "邮箱格式不正确！",
            "required": "邮箱不能为空",
        }
    )

    # 重写username字段的局部钩子
    def clean_username(self):
        username = self.cleaned_data.get("username")
        is_exist = models.UserInfo.objects.filter(username=username)
        if is_exist:
            # 表示用户名已注册
            self.add_error("username", ValidationError("用户名已存在"))
        else:
            return username

    # 重写email字段的局部钩子
    def clean_email(self):
        email = self.cleaned_data.get("email")
        is_exist = models.UserInfo.objects.filter(email=email)
        if is_exist:
            # 表示邮箱已注册
            self.add_error("email", ValidationError("邮箱已被注册"))
        else:
            return email

    # 重写全局的钩子函数，对确认密码做校验
    def clean(self):
        password = self.cleaned_data.get("password")
        re_password = self.cleaned_data.get("re_password")

        if re_password and re_password != password:
            self.add_error("re_password", ValidationError("两次密码不一致"))
        else:
            return self.cleaned_data


class BlogForm(forms.Form):
    title = forms.CharField(
        max_length=64,
        label="博客名",
        widget=forms.widgets.TextInput(
            attrs={"class": "form-control"},
        )
    )
    site =forms.CharField(
        max_length=32,
        label="站点",
        widget=forms.widgets.TextInput(
            attrs={"class": "form-control"},
        )
    )  # 个人博客域名
    theme = forms.CharField(
        max_length=32,
        label="博客主题",
        widget=forms.widgets.TextInput(
            attrs={"class": "form-control"},
        )
    )  # 博客主题

blog/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.contrib import auth
from django.http import JsonResponse
from geetest import GeetestLib
from . import models
from . import forms
import json
import os
from django.conf import settings
from django.db.models import F


# Create your views here.


def login(request):
    if request.method == 'POST':
        ret = {'status': 0, "msg": ''}
        username = request.POST.get('username')
        password = request.POST.get('password')
        # 获取极验 滑动验证码相关的参数
        gt = GeetestLib(pc_geetest_id, pc_geetest_key)
        challenge = request.POST.get(gt.FN_CHALLENGE, '')
        validate = request.POST.get(gt.FN_VALIDATE, '')
        seccode = request.POST.get(gt.FN_SECCODE, '')
        status = request.session[gt.GT_STATUS_SESSION_KEY]
        user_id = request.session["user_id"]

        if status:
            result = gt.success_validate(challenge, validate, seccode, user_id)
        else:
            result = gt.failback_validate(challenge, validate, seccode)
        if result:
            # 利用auth模块做用户名和密码的校验
            user = auth.authenticate(username=username, password=password)
            if user:
                # 用户名密码正确
                # 给用户做登录
                auth.login(request, user)  # 将登录用户赋值给 request.user
                ret["msg"] = "/index/"
            else:
                # 用户名密码错误
                ret["status"] = 1
                ret["msg"] = "用户名或密码错误！"
            return JsonResponse(ret)
    else:
        return render(request, 'login.html', )


def index(request):
    article_list = models.Article.objects.all().order_by("-nid")
    return render(request, 'index.html', locals())


def logout(request):
    auth.logout(request)
    return redirect("/login/")


# 请在官网申请ID使用，示例ID不可使用
pc_geetest_id = "b46d1900d0a894591916ea94ea91bd2c"
pc_geetest_key = "36fc3fe98530eea08dfc6ce76e3d24c4"


# 处理极验 获取验证码的视图
def get_geetest(request):
    user_id = 'test'
    gt = GeetestLib(pc_geetest_id, pc_geetest_key)
    status = gt.pre_process(user_id)
    request.session[gt.GT_STATUS_SESSION_KEY] = status
    request.session["user_id"] = user_id
    response_str = gt.get_response_str()
    return HttpResponse(response_str)


def register(request):
    if request.method == "POST":
        print(request.POST)
        ret = {"status": 0, "msg": ""}
        form_obj = forms.RegForm(request.POST)
        if form_obj.is_valid():
            # 校验通过，去数据库创建一个新的用户
            form_obj.cleaned_data.pop("re_password")
            avatar_img = request.FILES.get("avatar")
            models.UserInfo.objects.create_user(**form_obj.cleaned_data, avatar=avatar_img)
            ret["msg"] = "/login/"
            return JsonResponse(ret)
        else:
            # print(form_obj.errors)
            ret["status"] = 1
            ret["msg"] = form_obj.errors
            return JsonResponse(ret)

    # 生成一个form对象

    form_obj = forms.RegForm()
    return render(request, 'register.html', locals())


def check_username_exist(request):
    ret = {'status': 0, 'msg': ''}
    username = request.GET.get('username')
    user = models.UserInfo.objects.filter(username=username)
    if user:
        ret['status'] = 1
        ret['msg'] = ' 用户名已注册'

    else:
        ret['msg'] = ' 可注册'
    return JsonResponse(ret)


def home(request, site, *args):
    # print(site,args)
    blog = models.Blog.objects.filter(site=site).first()

    if not blog:
        return HttpResponse("404")
    else:
        username = blog.userinfo.username
        user = blog.userinfo
        article_list = models.Article.objects.filter(user=blog.userinfo).order_by("-nid")
        return render(request, 'blog.html', locals())


def tag(request, site, tag):
    blog = models.Blog.objects.filter(site=site).first()
    if not blog:
        return HttpResponse("404")
    else:
        username = blog.userinfo.username
        user = blog.userinfo
        article_list = models.Article.objects.filter(user=blog.userinfo, article2tag__tag__title=tag).order_by("-nid")
        return render(request, 'blog.html', locals())


def category(request, site, category):
    blog = models.Blog.objects.filter(site=site).first()
    if not blog:
        return HttpResponse("404")
    else:
        username = blog.userinfo.username
        user = blog.userinfo
        article_list = models.Article.objects.filter(user=user, category__title=category).order_by("-nid")
        # print(article_list)
        return render(request, 'blog.html', locals())


def article(request, site, article_id):
    blog = models.Blog.objects.filter(site=site).first()
    if blog:
        username = blog.userinfo.username
        user = blog.userinfo
        article = models.Article.objects.filter(nid=article_id, user=user).first()
        comment_list = models.Comment.objects.filter(article=article)
        if article:
            return render(request, 'article.html', locals())
        else:
            return HttpResponse("404")
    else:
        return HttpResponse("404")


def blog_reg(request):
    if request.method == 'POST':
        print(request.POST)
        ret = {"status": 0, "msg": ""}
        form_obj = forms.BlogForm(request.POST)
        if form_obj.is_valid():
            blog = models.Blog.objects.create(**form_obj.cleaned_data)
            models.UserInfo.objects.filter(username=request.user).update(blog=blog)
            ret["msg"] = "/blog/%s" % blog.site
            return JsonResponse(ret)
        else:
            # print(form_obj.errors)
            ret["status"] = 1
            ret["msg"] = form_obj.errors
            return JsonResponse(ret)

    blog_form = forms.BlogForm()

    return render(request, "blog-reg.html", locals())


def up_down(request):
    article_id = request.POST.get('article_id')
    is_up = json.loads(request.POST.get('is_up'))
    user = request.user
    response = {"state": True}
    try:
        models.ArticleUpDown.objects.create(user=user, article_id=article_id, is_up=is_up)
        models.Article.objects.filter(nid=article_id).update(up_count=F("up_count") + 1)

    except Exception as e:
        response["state"] = False
        response["fisrt_action"] = models.ArticleUpDown.objects.filter(user=user, article_id=article_id).first().is_up

    return JsonResponse(response)


def comment(request):
    content = request.POST.get("content")
    parent_comment_id = request.POST.get("parent_comment_id")
    article_id = request.POST.get("article_id")
    user_id = request.POST.get("user_id")
    comment = models.Comment.objects.create(
        content=content,
        parent_comment_id=parent_comment_id,
        article_id=article_id,
        user_id=user_id
    )
    models.Article.objects.filter(nid=article_id).update(comment_count=F("comment_count") + 1)
    # print(comment)
    return HttpResponse("评论成功")


def create(request):
    if request.method == "POST":
        title = request.POST.get('title')
        article_content = request.POST.get('content')
        user = request.user
        from bs4 import BeautifulSoup
        bs = BeautifulSoup(article_content, "html.parser")
        desc = bs.text[0:150] + "..."
        # 过滤非法标签
        for tag in bs.find_all():
            if tag.name in ["script", "link"]:
                tag.decompose()
        article_obj = models.Article.objects.create(user=user, title=title, desc=desc)
        models.ArticleDetail.objects.create(content=str(bs), article=article_obj)
        return HttpResponse("添加成功")
    return render(request, "blog-create.html")


def upload(request):
    print(request.FILES)
    obj = request.FILES.get("upload_img")
    print("name", obj.name)
    path = os.path.join(settings.MEDIA_ROOT, "add_article_img", obj.name)
    with open(path, "wb") as f:
        for line in obj:
            f.write(line)
    res = {
        "error": 0,
        "url": "/media/add_article_img/" + obj.name
    }
    return HttpResponse(json.dumps(res))

templates/article.html
{% extends 'base.html' %}

{% block page-main %}
    <div class="article-detail">
        <h1>{{ article.title }}</h1>
        <p>{{ article.articledetail.content|safe }}</p>
    </div>

    <div id="div_digg" nid="{{ article.nid }}">

        <div class="diggit action">
            <span class="diggnum" id="digg_count">{{ article.up_count }}</span>
        </div>
        <div class="buryit action">
            <span class="burynum" id="bury_count">{{ article.down_count }}</span>
        </div>
        <div class="clear"></div>
        {% if not request.user.username %}
         <div><h3 class="panel-title"><a href="/login/">请登录点赞</a></h3></div>
        {% endif %}
        <div class="diggword" id="digg_tips" style="color: red;"></div>
    </div>
    <div class="panel panel-info" style="clear: both">
        <h3>评论</h3>
        {% for comment in comment_list %}
            <div class="panel-heading">
                <h3 class="panel-title">#{{ forloop.counter }}楼 {{ comment.user }}-{{ comment.create_time }}</h3>
                {% if comment.parent_comment_id %}
                    <h3 class="panel-title">回复<h3
                            class="panel-title">{{ comment.parent_comment.user }}-{{ comment.parent_comment.content }}</h3>
                    </h3>
                {% endif %}
            </div>
            <div class="panel-body" comment_id="{{ comment.nid }}" username="{{ comment.user }}">
                <div>{{ comment.content }}</div>
                <label for="comment-area" style="float: right" onclick="reply(this);"><a>回复</a></label>
            </div>
        {% endfor %}
    </div>
    <div class="panel panel-success">
    {% if request.user.username %}
        <div class="panel-heading">
            <h3 class="panel-title">发表评论</h3>
        </div>
        <div class="panel-body">
            <p class="reply-info" reply_id=""></p>
            <textarea name="content" id="comment-area" cols="90" rows="10"></textarea>
            <p class="btn-success" id="comment_success"></p>
            <p><input type="button" value="提交" id="comment-buttom"></p>
        </div>
    {% else %}
        <div class="panel-heading">
            <h3 class="panel-title"><a href="/login/">请登录评论</a></h3>
        </div>
    {% endif %}

    </div>


    {% csrf_token %}
    <script>
        function reply(ths) {
            var reply_id = $(ths).parent().attr("comment_id");
            var username = $(ths).parent().attr("username");
            $(".reply-info").attr("reply_id",reply_id);
            $(".reply-info").text("@"+username);


        }
        $("#comment-buttom").click(function () {
            var content = $(this).parent().prev().prev().val();
            var parent_comment_id = $(".reply-info").attr("reply_id");
            console.log(parent_comment_id);
            var article_id = {{ article.nid }};
            $.ajax({
                url:"/blog/comment/",
                type:"post",
                data:{
                    "content":content,
                    "parent_comment_id":parent_comment_id,
                    "article_id":article_id,
                    "user_id":{{ request.user.nid }},
                    "csrfmiddlewaretoken":$("[name='csrfmiddlewaretoken']").val(),
                },
                success:function (ret) {
                    $("#comment_success").text(ret);
                    $("#comment-area").val("");
                    $(".reply-info").attr("reply_id","");
                    $(".reply-info").text("");
                }
            })
        })
        $("#div_digg").find(".action").click(function () {
            // 点赞或踩灭
            var data = {};

            data["is_up"] = $(this).hasClass("diggit");
            data["article_id"] = $("#div_digg").attr("nid");
            data["csrfmiddlewaretoken"] = $("[name='csrfmiddlewaretoken']").val();
            $.ajax({
                url: "/blog/up_down/",
                type: "post",
                data: data,
                dataType: 'json',
                success: function (arg) {
                    if (arg.state) {// 赞或者灭成功

                        if (data["is_up"]) {
                            var val = $("#digg_count").text();
                            val = parseInt(val) + 1;
                            $("#digg_count").text(val);
                        } else {
                            var val = $("#bury_count").text();
                            val = parseInt(val) + 1;
                            $("#bury_count").text(val);
                        }
                    }
                    else {    // 重复提交

                        if (arg.fisrt_action) {
                            $("#digg_tips").html("您已经推荐过");
                        } else {
                            $("#digg_tips").html("您已经反对过");
                        }
                        setTimeout(function () {
                            $("#digg_tips").html("")
                        }, 1000)
                    }
                }
            })
        })
    </script>
{% endblock %}

templates/blog-create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>The blog</title>
    <link rel="stylesheet" href="/static/plugins/bootstrap-3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/plugins/font-awesome-4.7.0/css/font-awesome.min.css">
    <script src="/static/js/jquery-3.3.1.js"></script>
    <script src="/static/plugins/bootstrap-3.3.7/js/bootstrap.min.js"></script>
    <script src="/static/kindeditor/kindeditor-all-min.js"></script>
</head>
<body>
<div class="container">
    <div class="panel panel-info">
        <div class="panel-heading">
            <h3 class="panel-title">编辑文章</h3>
        </div>
        <div class="panel-body">
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <label for="title">文章标题</label>
                <input type="text" name="title" id="title">
                <textarea name="content" id="content"></textarea>
                <button type="submit">提交文章</button>
            </form>
        </div>
    </div>
</div>
<script>
    $(function () {
        initKindEditor();
    });

    function initKindEditor() {
        var kind = KindEditor.create('#content', {
            width: '100%',       // 文本框宽度(可以百分比或像素)
            height: '300px',     // 文本框高度(只能像素)
            minWidth: 200,       // 最小宽度（数字）
            minHeight: 400,      // 最小高度（数字）
            resizeType: 0,
            uploadJson: "/upload/",
            filePostName: "upload_img",
            extraFileUploadParams: {
                csrfmiddlewaretoken: $("[name='csrfmiddlewaretoken']").val()
            },     //添加上csrftoken
        });
    }
</script>
</body>
</html>

templates/left_menu.html
<div class="panel panel-primary">
<div class="panel-heading">文章分类</div>
<div class="panel-body">
    {% for category in category_list %}
        <p><a href="/blog/{{ site }}/category/{{ category.title }}/">{{ category.title }}({{ category.c }})</a></p>
    {% endfor %}

</div>
</div>
<div class="panel panel-warning">
    <div class="panel-heading">文章标签</div>
    <div class="panel-body">
        {% for tag in tag_list %}
            <p><a href="/blog/{{ site }}/tag/{{ tag.title }}/">{{ tag.title }}({{ tag.c }})</a></p>
        {% endfor %}

    </div>
</div>

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册页面</title>
    <link rel="stylesheet" href="/static/plugins/bootstrap-3.3.7/css/bootstrap.min.css">
    <style>
        body {
            padding: 0;
            margin: 0;
            background: #bce8f1;
        }
    </style>
</head>
<body>
<div class="container" style="margin:250px 300px">
    <div style="margin-bottom: 80px"><h2 style="text-align:center">博客注册页面</h2></div>
    <form class="form-horizontal">
        {% csrf_token %}
        <div class="form-group">
            <label for="{{ form_obj.username.id_for_label }}"
                   class="col-sm-2 control-label">{{ form_obj.username.label }}</label>
            <div class="col-sm-8">
                {{ form_obj.username }}
                <span class="help-block">{{ form_obj.username.errors.0 }}</span>
            </div>
        </div>

        <div class="form-group">
            <label for="{{ form_obj.password.id_for_label }}"
                   class="col-sm-2 control-label">{{ form_obj.password.label }}</label>
            <div class="col-sm-8">
                {{ form_obj.password }}
                <span class="help-block">{{ form_obj.password.errors.0 }}</span>
            </div>
        </div>

        <div class="form-group">
            <label for="{{ form_obj.re_password.id_for_label }}"
                   class="col-sm-2 control-label">{{ form_obj.re_password.label }}</label>
            <div class="col-sm-8">
                {{ form_obj.re_password }}
                <span class="help-block">{{ form_obj.re_password.errors.0 }}</span>
            </div>
        </div>

        <div class="form-group">
            <label for="{{ form_obj.email.id_for_label }}"
                   class="col-sm-2 control-label">{{ form_obj.email.label }}</label>
            <div class="col-sm-8">
                {{ form_obj.email }}
                <span class="help-block">{{ form_obj.email.errors.0 }}</span>
            </div>
        </div>

        <div class="form-group">
            <label
                    class="col-sm-2 control-label">头像</label>
            <div class="col-sm-8">
                <label for="id_avatar"><img id="avatar-img" src="/static/avatars/default.png" alt=""></label>
                <input accept="image/*" type="file" name="avatar" id="id_avatar" style="display: none">
                <span class="help-block"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <div><span class="login-error btn-danger"></span></div>
                <button type="button" class="btn btn-default" id="register-button">注册</button>
            </div>
        </div>
    </form>
    <div style="float: right "><a href="/login"><h2>已有账号？直接登录</h2></a></div>
</div>

<script src="/static/js/jquery-3.3.1.js"></script>
<script src="/static/plugins/bootstrap-3.3.7/js/bootstrap.min.js"></script>
<!-- 引入封装了failback的接口--initGeetest -->
<script src="http://static.geetest.com/static/tools/gt.js"></script>
<script>
    // 找到头像的input标签绑定change事件
    $("#id_avatar").change(function () {
        // 1. 创建一个读取文件的对象
        var fileReader = new FileReader();
        // 取到当前选中的头像文件
        // console.log(this.files[0]);
        // 读取你选中的那个文件
        fileReader.readAsDataURL(this.files[0]);  // 读取文件是需要时间的
        fileReader.onload = function () {
            // 2. 等上一步读完文件之后才 把图片加载到img标签中
            $("#avatar-img").attr("src", fileReader.result);
        };
    });
    $(function () {
        bindRegister();
    })
    function bindRegister() {
        $("#register-button").click(function () {
        var formData = new FormData();
        formData.append("username", $("#id_username").val());
        formData.append("password", $("#id_password").val());
        formData.append("re_password", $("#id_re_password").val());
        formData.append("email", $("#id_email").val());
        formData.append("csrfmiddlewaretoken", $("[name='csrfmiddlewaretoken']").val());
        formData.append("avatar", $("#id_avatar")[0].files[0]);
        console.log(formData)
        $.ajax({
            url:"/register/",
            type:"post",
            data:formData,
            processData: false,  // 告诉jQuery不要处理我的数据
            contentType: false,  // 告诉jQuery不要设置content类型
            success:function (data) {
                if (!data.status) {
                    // 没有错误就跳转到指定页面
                    location.href = data.msg;
                } else {
                    // 有错误就展示错误
                    // console.log(data.msg);
                    // 将报错信息填写到页面上
                    $.each(data.msg, function (k, v) {
                        // console.log("id_"+k, v[0]);
                        // console.log($("#id_"+k));
                        $("#id_" + k).next("span").text(v[0]).parent().parent().addClass("has-error");
                    })

                }
            }
        })
        })
    }
    // 将所有的input框绑定获取焦点的事件，将所有的错误信息清空
    $("form input").focus(function () {
        $(this).next().text("").parent().parent().removeClass("has-error");
    });

    // 给username input框绑定一个失去焦点的事件，失去焦点之后就校验用户名是否已被注册
    {#$("#id_username").blur(function () {#}
    $("#id_username").on("input", function () {
        // 取到用户填写的值
        var username = $(this).val();
        // 发请求
        $.ajax({
            url: "/check_username_exist/",
            type: "get",
            data: {"username": username},
            success: function (data) {
                if (data.status){
                    // 用户名已被注册
                    $("#id_username").next().text(data.msg).parent().parent().addClass("has-error");
                }else {
                    $("#id_username").next().text(data.msg)
                }
            }
        })
    })
</script>

</body>
</html>